[book]
title = "Software Engineering Study Guide"
description = "A study guide for software engineering interviews"
authors = ["Austin Schwarm"]
language = "en"
multilingual = false
src = "src"

[output.html]
mathjax-support = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2